import { supabase } from './supabase';
import jsPDF from 'jspdf';

export async function fetchReportData(organizationId, projectId = null, type = 'weekly') {
  try {
    const { data: organization } = await supabase
      .from('organizations')
      .select('*')
      .eq('id', organizationId)
      .single();

    let projectQuery = supabase
      .from('projects')
      .select('*')
      .eq('organization_id', organizationId);
    
    if (projectId) {
      projectQuery = projectQuery.eq('id', projectId);
    }
    
    const { data: projects } = await projectQuery;

    let taskQuery = supabase.from('tasks').select('*');
    
    if (projectId) {
      taskQuery = taskQuery.eq('project_id', projectId);
    } else if (projects) {
      const projectIds = projects.map(p => p.id);
      taskQuery = taskQuery.in('project_id', projectIds);
    }
    
    const { data: tasks } = taskQuery;

    const now = new Date();
    const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
    const monthAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
    
    let dateFilter = type === 'weekly' ? weekAgo : monthAgo;
    
    const { data: meetings } = await supabase
      .from('meetings')
      .select('*')
      .eq('organization_id', organizationId)
      .gte('created_at', dateFilter.toISOString())
      .order('created_at', { ascending: false });

    const { data: members } = await supabase
      .from('organization_members')
      .select('user_id, role')
      .eq('organization_id', organizationId);

    let deliverablesQuery = supabase
      .from('deliverables')
      .select('*')
      .eq('organization_id', organizationId);
    
    if (projectId) {
      deliverablesQuery = deliverablesQuery.eq('project_id', projectId);
    }
    
    const { data: deliverables } = await deliverablesQuery;

    let feedbackQuery = supabase
      .from('client_feedback')
      .select('*')
      .eq('organization_id', organizationId);
    
    if (projectId) {
      feedbackQuery = feedbackQuery.eq('project_id', projectId);
    }
    
    const { data: feedbacks } = await feedbackQuery;

    return {
      organization,
      projects: projects || [],
      tasks: tasks || [],
      meetings: meetings || [],
      members: members || [],
      deliverables: deliverables || [],
      feedbacks: feedbacks || [],
      period: type === 'weekly' ? 'Weekly' : (type === 'monthly' ? 'Monthly' : 'Client'),
      generatedAt: new Date().toISOString(),
    };
  } catch (error) {
    console.error('Error fetching report data:', error);
    throw error;
  }
}

export function generateFormattedReport(data) {
  const { organization, projects, tasks, meetings, members, deliverables, feedbacks, period } = data;
  
  const totalTasks = tasks.length;
  const completedTasks = tasks.filter(t => t.status === 'completed').length;
  const inProgressTasks = tasks.filter(t => t.status === 'in_progress').length;
  const pendingTasks = tasks.filter(t => t.status === 'todo' || t.status === 'backlog').length;
  const reviewTasks = tasks.filter(t => t.status === 'review').length;
  const completionRate = totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0;
  
  const urgentTasks = tasks.filter(t => t.priority === 'urgent').length;
  const highPriorityTasks = tasks.filter(t => t.priority === 'high').length;
  
  const totalMeetings = meetings.length;
  const completedMeetings = meetings.filter(m => m.status === 'completed').length;
  
  const totalDeliverables = deliverables.length;
  const approvedDeliverables = deliverables.filter(d => d.status === 'approved').length;
  const pendingDeliverables = deliverables.filter(d => d.status === 'pending').length;
  
  const totalFeedbacks = feedbacks.length;
  const openFeedbacks = feedbacks.filter(f => f.status === 'open').length;
  
  const now = new Date();
  const formattedDate = now.toLocaleDateString('en-US', { 
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' 
  });
  const formattedTime = now.toLocaleTimeString('en-US', { 
    hour: '2-digit', minute: '2-digit' 
  });

  let report = '';
  
  // Header
  report += `============================================\n`;
  report += `       MEETINGFLOW AI REPORT\n`;
  report += `============================================\n\n`;
  
  // Organization Info
  report += `--- ORGANIZATION INFORMATION ---\n\n`;
  report += `  Organization Name : ${organization?.name || 'N/A'}\n`;
  report += `  Report Type       : ${period} Report\n`;
  report += `  Generated On      : ${formattedDate} at ${formattedTime}\n`;
  report += `  Generated By      : MeetingFlow AI\n`;
  report += `  Period Covered    : Last ${period === 'Weekly' ? '7' : '30'} days\n\n`;
  
  // Executive Summary
  report += `--- EXECUTIVE SUMMARY ---\n\n`;
  report += `  This ${period.toLowerCase()} report provides an overview of project activities,\n`;
  report += `  task progress, meeting summaries, and team performance\n`;
  report += `  for ${organization?.name || 'your organization'}.\n\n`;
  
  // Key Metrics
  report += `--- KEY METRICS ---\n\n`;
  report += `  Total Projects      : ${projects.length}\n`;
  report += `  Total Tasks         : ${totalTasks}\n`;
  report += `  Completed Tasks     : ${completedTasks} (${completionRate}%)\n`;
  report += `  In Progress         : ${inProgressTasks}\n`;
  report += `  Pending Tasks       : ${pendingTasks}\n`;
  report += `  In Review           : ${reviewTasks}\n`;
  report += `  Urgent Tasks        : ${urgentTasks}\n`;
  report += `  High Priority       : ${highPriorityTasks}\n`;
  report += `  Total Meetings      : ${totalMeetings}\n`;
  report += `  Deliverables        : ${totalDeliverables} (${approvedDeliverables} approved)\n`;
  report += `  Client Feedbacks    : ${totalFeedbacks} (${openFeedbacks} open)\n`;
  report += `  Team Members        : ${members.length}\n`;
  report += `  Completion Rate     : ${completionRate}%\n\n`;
  
  // Project Details
  if (projects.length > 0) {
    report += `--- PROJECT DETAILS ---\n\n`;
    
    projects.forEach((project, index) => {
      const projectTasks = tasks.filter(t => t.project_id === project.id);
      const projectCompleted = projectTasks.filter(t => t.status === 'completed').length;
      const projectTotal = projectTasks.length;
      const projectRate = projectTotal > 0 ? Math.round((projectCompleted / projectTotal) * 100) : 0;
      
      report += `  ${index + 1}. ${project.name}\n`;
      report += `     Status        : ${project.status || 'N/A'}\n`;
      report += `     Tasks         : ${projectCompleted}/${projectTotal} completed (${projectRate}%)\n`;
      if (project.description) {
        report += `     Description   : ${project.description}\n`;
      }
      report += `\n`;
    });
  }
  
  // Task Breakdown
  if (tasks.length > 0) {
    report += `--- TASK BREAKDOWN ---\n\n`;
    
    const recentCompleted = tasks.filter(t => t.status === 'completed').slice(0, 10);
    if (recentCompleted.length > 0) {
      report += `  Completed Tasks:\n`;
      recentCompleted.forEach(task => {
        report += `    - ${task.title} (Priority: ${task.priority})\n`;
      });
      report += `\n`;
    }
    
    const inProgress = tasks.filter(t => t.status === 'in_progress').slice(0, 10);
    if (inProgress.length > 0) {
      report += `  In Progress:\n`;
      inProgress.forEach(task => {
        report += `    - ${task.title} (Priority: ${task.priority})\n`;
      });
      report += `\n`;
    }
    
    const urgentPending = tasks.filter(t => 
      (t.priority === 'urgent' || t.priority === 'high') && 
      t.status !== 'completed'
    ).slice(0, 10);
    if (urgentPending.length > 0) {
      report += `  Urgent/High Priority Pending:\n`;
      urgentPending.forEach(task => {
        report += `    - ${task.title} (Status: ${task.status}, Priority: ${task.priority})\n`;
      });
      report += `\n`;
    }
  }
  
  // Meetings Summary
  if (meetings.length > 0) {
    report += `--- MEETINGS SUMMARY ---\n\n`;
    
    meetings.slice(0, 10).forEach((meeting, index) => {
      report += `  ${index + 1}. ${meeting.title || 'Untitled Meeting'}\n`;
      report += `     Date      : ${new Date(meeting.created_at).toLocaleDateString()}\n`;
      report += `     Status    : ${meeting.status || 'N/A'}\n`;
      if (meeting.summary) {
        const shortSummary = meeting.summary.length > 100 
          ? meeting.summary.substring(0, 100) + '...' 
          : meeting.summary;
        report += `     Summary   : ${shortSummary}\n`;
      }
      report += `\n`;
    });
  }
  
  // Deliverables Status
  if (deliverables.length > 0) {
    report += `--- DELIVERABLES STATUS ---\n\n`;
    report += `  Total      : ${totalDeliverables}\n`;
    report += `  Approved   : ${approvedDeliverables}\n`;
    report += `  Pending    : ${pendingDeliverables}\n`;
    report += `  In Review  : ${deliverables.filter(d => d.status === 'in_review').length}\n`;
    report += `  Rejected   : ${deliverables.filter(d => d.status === 'rejected').length}\n\n`;
    
    deliverables.slice(0, 10).forEach(d => {
      report += `  - ${d.title} (Status: ${d.status})\n`;
      if (d.due_date) {
        report += `    Due: ${new Date(d.due_date).toLocaleDateString()}\n`;
      }
    });
    report += `\n`;
  }
  
  // Client Feedback
  if (feedbacks.length > 0) {
    report += `--- CLIENT FEEDBACK ---\n\n`;
    report += `  Total Feedbacks  : ${totalFeedbacks}\n`;
    report += `  Open Feedbacks   : ${openFeedbacks}\n`;
    report += `  Resolved         : ${feedbacks.filter(f => f.status === 'resolved').length}\n\n`;
    
    feedbacks.slice(0, 5).forEach(fb => {
      report += `  - ${fb.feedback.substring(0, 80)}${fb.feedback.length > 80 ? '...' : ''}\n`;
      if (fb.rating) {
        report += `    Rating: ${fb.rating}/5\n`;
      }
      report += `    Status: ${fb.status} | ${new Date(fb.created_at).toLocaleDateString()}\n\n`;
    });
  }
  
  // Recommendations
  report += `--- AI RECOMMENDATIONS ---\n\n`;
  if (urgentTasks > 0) report += `  - Address ${urgentTasks} urgent task(s) immediately.\n`;
  if (completionRate < 50) report += `  - Task completion rate is below 50%. Consider reviewing workload.\n`;
  if (pendingDeliverables > 3) report += `  - ${pendingDeliverables} deliverables pending approval. Follow up with clients.\n`;
  if (openFeedbacks > 0) report += `  - ${openFeedbacks} client feedback items need attention.\n`;
  if (totalMeetings === 0) report += `  - No meetings recorded this period. Consider scheduling team sync-ups.\n`;
  report += `  - Regularly update task statuses for accurate tracking.\n`;
  report += `  - Review this report weekly to track progress trends.\n\n`;
  
  // Footer
  report += `============================================\n`;
  report += `  Report Generated by MeetingFlow AI\n`;
  report += `  ${organization?.name || 'Organization'} - ${formattedDate}\n`;
  report += `============================================\n`;
  
  return report;
}

export function downloadReport(content, filename) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function downloadReportAsPDF(content, filename, orgName) {
  const doc = new jsPDF();
  
  doc.setProperties({
    title: filename.replace('.pdf', ''),
    subject: 'MeetingFlow AI Report',
    author: orgName || 'MeetingFlow AI',
    creator: 'MeetingFlow AI'
  });

  // RGB Colors
  const goldColor = [219, 153, 65];
  const darkColor = [7, 17, 29];
  const charcoalColor = [57, 68, 77];
  const grayColor = [93, 93, 93];
  const lightGold = [245, 240, 232];

  let yPos = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);

  // Clean text helper
  const cleanText = (text) => {
    if (!text) return '';
    return text
      .replace(/[^\x20-\x7E\xA0-\xFF\u0152\u0153\u0160\u0161\u0178\u017D\u017E\u0192\u02C6\u02DC\u2013\u2014\u2018\u2019\u201A\u201C\u201D\u201E\u2020\u2021\u2022\u2026\u2030\u2032\u2033\u2039\u203A\u203E\u2044\u20AC\u2122\u2212\uFB01\uFB02]/g, '')
      .replace(/\s+/g, ' ')
      .trim();
  };

  // Add text with wrapping
  const addText = (text, x, y, maxWidth, fontSize = 10, color = darkColor, isBold = false) => {
    const clean = cleanText(text);
    if (!clean || clean.length === 0) return y;
    
    doc.setFontSize(fontSize);
    doc.setTextColor(color[0], color[1], color[2]);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    const lines = doc.splitTextToSize(clean, maxWidth);
    doc.text(lines, x, y);
    return y + (lines.length * (fontSize * 0.42));
  };

  // === HEADER ===
  doc.setFillColor(darkColor[0], darkColor[1], darkColor[2]);
  doc.rect(0, 0, pageWidth, 45, 'F');
  
  doc.setFillColor(goldColor[0], goldColor[1], goldColor[2]);
  doc.rect(0, 45, pageWidth, 3, 'F');

  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.text('MEETINGFLOW AI REPORT', margin, 25);

  doc.setFontSize(10);
  doc.setTextColor(goldColor[0], goldColor[1], goldColor[2]);
  doc.setFont('helvetica', 'normal');
  doc.text('Meeting Intelligence & Project Analytics', margin, 35);

  yPos = 58;

  // === ORGANIZATION INFO BOX ===
  doc.setDrawColor(goldColor[0], goldColor[1], goldColor[2]);
  doc.setFillColor(lightGold[0], lightGold[1], lightGold[2]);
  doc.roundedRect(margin, yPos, contentWidth, 28, 3, 3, 'FD');
  
  doc.setFontSize(12);
  doc.setTextColor(darkColor[0], darkColor[1], darkColor[2]);
  doc.setFont('helvetica', 'bold');
  doc.text('Organization:', margin + 5, yPos + 10);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(orgName || 'N/A', margin + 55, yPos + 10);
  
  doc.setFontSize(9);
  doc.setTextColor(grayColor[0], grayColor[1], grayColor[2]);
  const reportDate = new Date().toLocaleDateString('en-US', { 
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' 
  });
  doc.text(`Generated: ${reportDate}`, margin + 5, yPos + 22);

  yPos += 40;

  // === PROCESS CONTENT ===
  const lines = content.split('\n');
  let currentSection = '';
  
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();
    const clean = cleanText(trimmed);
    
    // New page check
    if (yPos > pageHeight - 30) {
      doc.setFontSize(8);
      doc.setTextColor(grayColor[0], grayColor[1], grayColor[2]);
      doc.setFont('helvetica', 'normal');
      doc.text(`Page ${doc.internal.getNumberOfPages()}`, pageWidth - margin, pageHeight - 15, { align: 'right' });
      doc.text(orgName || 'MeetingFlow AI', margin, pageHeight - 15);
      doc.addPage();
      yPos = 25;
    }
    
    // Skip empty lines
    if (!clean || clean.length === 0) {
      yPos += 3;
      continue;
    }
    
    // Skip separator lines
    if (clean.match(/^[=]+$/) || clean.match(/^[-]+$/)) {
      yPos += 2;
      continue;
    }
    
    // Section headers (lines with --- TEXT ---)
    if (clean.match(/^--- .+ ---$/)) {
      const sectionTitle = clean.replace(/---/g, '').trim();
      currentSection = sectionTitle;
      
      yPos += 5;
      doc.setFontSize(13);
      doc.setTextColor(goldColor[0], goldColor[1], goldColor[2]);
      doc.setFont('helvetica', 'bold');
      doc.text(sectionTitle, margin, yPos);
      
      // Underline
      yPos += 3;
      doc.setDrawColor(goldColor[0], goldColor[1], goldColor[2]);
      doc.setLineWidth(0.5);
      doc.line(margin, yPos, margin + Math.min(sectionTitle.length * 5, contentWidth), yPos);
      yPos += 8;
      continue;
    }
    
    // Main title
    if (clean.includes('MEETINGFLOW AI REPORT')) {
      continue; // Already in header
    }
    
    // Key-value pairs (lines with colons)
    if (clean.includes(':') && !clean.startsWith('-') && !clean.match(/^\d+\./)) {
      const colonIndex = clean.indexOf(':');
      const key = clean.substring(0, colonIndex + 1).trim();
      const value = clean.substring(colonIndex + 1).trim();
      
      doc.setFontSize(9);
      doc.setTextColor(grayColor[0], grayColor[1], grayColor[2]);
      doc.setFont('helvetica', 'bold');
      doc.text(key, margin + 3, yPos);
      
      const keyWidth = doc.getTextWidth(key + ' ');
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(darkColor[0], darkColor[1], darkColor[2]);
      
      if (value && doc.getTextWidth(value) > contentWidth - keyWidth - 10) {
        const valueLines = doc.splitTextToSize(value, contentWidth - keyWidth - 10);
        doc.text(valueLines, margin + 3 + keyWidth, yPos);
        yPos += (valueLines.length * 5);
      } else {
        doc.text(value || '', margin + 3 + keyWidth, yPos);
        yPos += 5;
      }
      continue;
    }
    
    // Bullet points and numbered items
    if (clean.startsWith('-') || clean.match(/^\d+\./)) {
      yPos = addText(clean, margin + 4, yPos, contentWidth - 8, 9, charcoalColor);
      yPos += 2;
      continue;
    }
    
    // Regular text
    yPos = addText(clean, margin, yPos, contentWidth, 9, charcoalColor);
    yPos += 2;
  }

  // === FINAL FOOTER ===
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    
    // Gold line at bottom
    doc.setDrawColor(goldColor[0], goldColor[1], goldColor[2]);
    doc.setLineWidth(0.5);
    doc.line(margin, pageHeight - 14, pageWidth - margin, pageHeight - 14);
    
    doc.setFontSize(7);
    doc.setTextColor(grayColor[0], grayColor[1], grayColor[2]);
    doc.setFont('helvetica', 'normal');
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin, pageHeight - 8, { align: 'right' });
    doc.text(`Generated by MeetingFlow AI for ${orgName || 'Organization'}`, margin, pageHeight - 8);
  }

  doc.save(filename);
}

export function generateFilename(orgName, type) {
  const date = new Date().toISOString().split('T')[0];
  const cleanName = orgName?.replace(/[^a-z0-9]/gi, '-').toLowerCase() || 'organization';
  return `${cleanName}-${type.toLowerCase()}-report-${date}.txt`;
}