import { useState } from 'react';
import { supabase } from '../lib/supabase';
import { useAuthStore } from '../store/authStore';
import { generateWeeklyReport, generateClientUpdate } from '../lib/ai';
import { 
  FileText, Download, Loader, Calendar, 
  TrendingUp, Users, CheckCircle, AlertCircle 
} from 'lucide-react';
import { toast } from 'react-hot-toast';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export default function ReportGenerator() {
  const [generating, setGenerating] = useState(false);
  const [report, setReport] = useState(null);
  const [reportType, setReportType] = useState('weekly');
  const [selectedProject, setSelectedProject] = useState('all');
  const [projects, setProjects] = useState([]);
  const [showPreview, setShowPreview] = useState(false);
  
  const organization = useAuthStore(state => state.organization);
  const user = useAuthStore(state => state.user);

  useState(() => {
    loadProjects();
  }, []);

  const loadProjects = async () => {
    const { data } = await supabase
      .from('projects')
      .select('*')
      .eq('organization_id', organization.id);
    
    if (data) setProjects(data);
  };

  const generateReport = async () => {
    setGenerating(true);
    try {
      // Gather data
      let projectData;
      
      if (selectedProject === 'all') {
        const { data: projects } = await supabase
          .from('projects')
          .select('*')
          .eq('organization_id', organization.id);
        
        const { data: tasks } = await supabase
          .from('tasks')
          .select('*')
          .in('project_id', projects?.map(p => p.id) || []);

        const { data: meetings } = await supabase
          .from('meetings')
          .select('*')
          .eq('organization_id', organization.id)
          .gte('created_at', new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString());

        projectData = {
          organization: organization.name,
          projects: projects || [],
          tasks: tasks || [],
          recentMeetings: meetings || [],
          timeframe: 'Weekly'
        };
      } else {
        const { data: project } = await supabase
          .from('projects')
          .select('*')
          .eq('id', selectedProject)
          .single();

        const { data: tasks } = await supabase
          .from('tasks')
          .select('*')
          .eq('project_id', selectedProject);

        projectData = {
          project: project,
          tasks: tasks || [],
          timeframe: 'Weekly'
        };
      }

      // Generate AI report
      const reportContent = reportType === 'client' 
        ? await generateClientUpdate(projectData)
        : await generateWeeklyReport(projectData);

      setReport({
        content: reportContent,
        type: reportType,
        data: projectData,
        generatedAt: new Date().toISOString()
      });
      
      setShowPreview(true);
      toast.success('Report generated!');
    } catch (error) {
      console.error('Report generation error:', error);
      toast.error('Failed to generate report');
    } finally {
      setGenerating(false);
    }
  };

  const exportToPDF = async () => {
    try {
      const doc = new jsPDF();
      
      // Add title
      doc.setFontSize(20);
      doc.setTextColor(37, 99, 235); // brand-600
      doc.text('MeetingFlow AI Report', 20, 20);
      
      doc.setFontSize(12);
      doc.setTextColor(100, 100, 100);
      doc.text(`Generated on ${new Date().toLocaleDateString()}`, 20, 30);
      
      // Add content
      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);
      
      const lines = doc.splitTextToSize(report.content, 170);
      doc.text(lines, 20, 40);
      
      // Add footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(`Generated by MeetingFlow AI for ${organization.name}`, 20, 280);
      
      // Save
      doc.save(`meetingflow-report-${Date.now()}.pdf`);
      toast.success('PDF downloaded!');
    } catch (error) {
      console.error('PDF export error:', error);
      toast.error('Failed to export PDF');
    }
  };

  const printReport = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      {/* Report Configuration */}
      <div className="bg-white rounded-xl shadow-sm border p-6">
        <h2 className="text-xl font-bold mb-4">Generate Report</h2>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
          <div>
            <label className="block text-sm font-medium mb-2">Report Type</label>
            <select
              value={reportType}
              onChange={(e) => setReportType(e.target.value)}
              className="w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-500"
            >
              <option value="weekly">Weekly Report</option>
              <option value="progress">Project Progress</option>
              <option value="team">Team Productivity</option>
              <option value="client">Client Update</option>
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium mb-2">Project</label>
            <select
              value={selectedProject}
              onChange={(e) => setSelectedProject(e.target.value)}
              className="w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-500"
            >
              <option value="all">All Projects</option>
              {projects.map(project => (
                <option key={project.id} value={project.id}>
                  {project.name}
                </option>
              ))}
            </select>
          </div>

          <div className="flex items-end">
            <button
              onClick={generateReport}
              disabled={generating}
              className="w-full px-4 py-2 bg-brand-600 text-white rounded-lg hover:bg-brand-700 disabled:opacity-50 flex items-center justify-center"
            >
              {generating ? (
                <>
                  <Loader className="animate-spin mr-2" size={18} />
                  Generating...
                </>
              ) : (
                <>
                  <FileText className="mr-2" size={18} />
                  Generate Report
                </>
              )}
            </button>
          </div>
        </div>

        {/* Quick Stats */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="p-3 bg-blue-50 rounded-lg">
            <div className="flex items-center space-x-2">
              <CheckCircle size={16} className="text-blue-600" />
              <span className="text-xs font-medium text-blue-600">Tasks Completed</span>
            </div>
            <p className="text-2xl font-bold mt-1">24</p>
          </div>
          <div className="p-3 bg-green-50 rounded-lg">
            <div className="flex items-center space-x-2">
              <TrendingUp size={16} className="text-green-600" />
              <span className="text-xs font-medium text-green-600">Productivity</span>
            </div>
            <p className="text-2xl font-bold mt-1">78%</p>
          </div>
          <div className="p-3 bg-purple-50 rounded-lg">
            <div className="flex items-center space-x-2">
              <Users size={16} className="text-purple-600" />
              <span className="text-xs font-medium text-purple-600">Team Members</span>
            </div>
            <p className="text-2xl font-bold mt-1">8</p>
          </div>
          <div className="p-3 bg-orange-50 rounded-lg">
            <div className="flex items-center space-x-2">
              <AlertCircle size={16} className="text-orange-600" />
              <span className="text-xs font-medium text-orange-600">Overdue Tasks</span>
            </div>
            <p className="text-2xl font-bold mt-1">3</p>
          </div>
        </div>
      </div>

      {/* Report Preview */}
      {showPreview && report && (
        <div className="bg-white rounded-xl shadow-sm border">
          <div className="p-6 border-b flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <FileText size={20} className="text-brand-600" />
              <div>
                <h3 className="font-semibold">Report Preview</h3>
                <p className="text-xs text-gray-500">
                  Generated {new Date(report.generatedAt).toLocaleString()}
                </p>
              </div>
            </div>
            <div className="flex space-x-2">
              <button
                onClick={printReport}
                className="px-3 py-1.5 text-sm border rounded-lg hover:bg-gray-50"
              >
                Print
              </button>
              <button
                onClick={exportToPDF}
                className="px-3 py-1.5 text-sm bg-brand-600 text-white rounded-lg hover:bg-brand-700 flex items-center"
              >
                <Download size={16} className="mr-1" />
                Download PDF
              </button>
            </div>
          </div>

          <div className="p-6 prose max-w-none" id="report-content">
            <div className="whitespace-pre-wrap">{report.content}</div>
          </div>
        </div>
      )}

      {/* Report History */}
      <div className="bg-white rounded-xl shadow-sm border p-6">
        <h3 className="font-semibold mb-4">Recent Reports</h3>
        <div className="space-y-2">
          {[1, 2, 3].map((i) => (
            <div key={i} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
              <div className="flex items-center space-x-3">
                <FileText size={18} className="text-gray-400" />
                <div>
                  <p className="text-sm font-medium">Weekly Report - Week {i}</p>
                  <p className="text-xs text-gray-500">
                    {new Date(Date.now() - i * 7 * 24 * 60 * 60 * 1000).toLocaleDateString()}
                  </p>
                </div>
              </div>
              <button className="text-sm text-brand-600 hover:text-brand-700">
                View
              </button>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}